server:
  port: 8200
#逻辑删除
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 #删除的值
      logic-not-delete-value: 0 #未删除的值
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/ylservice?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8